### PR TITLE
feat(ci): add ci github action

### PR DESCRIPTION
**Pull request by JellyBellyDev**
[feat/ci-github-action 6469be8] feat(ci): add ci github action

ref #2

### CODE REVIEW

**Review by brainrepo — COMMENTED** [review]
For the name change, I propose an RFC to define the definitive name of this tool

**Comment by JellyBellyDev** [comment]
> For the name change, I propose an RFC to define the definitive name of this tool

I'm sorry, I thought it was already official!  
Do you want me to revert my modification?

**Review by LucaRainone — APPROVED** [review]

**Comment by brainrepo** [comment]
> eady official!
> Do you want me to revert my modificatio

Mh I think that we can move the renaming to another issue/pr. I am happy to merge it if we remove the naming changes.

**Comment by JellyBellyDev** [comment]
> > eady official!
> > Do you want me to revert my modificatio
> 
> Mh I think that we can move the renaming to another issue/pr. I am happy to merge it if we remove the naming changes.

Done! ;)

**Review by brainrepo — APPROVED** [review]

**Comment by brainrepo** [comment]
For me is ok feel free to merge

**Pull request merged**
